version: '3.3'
services:
    mssql:
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssW0rd
        ports:
            - '1433:1433'
        container_name: mssql
        image: 'mcr.microsoft.com/mssql/server:2017-CU8-ubuntu'
